//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchNo
    {
        public int Id { get; set; }
        public string BatnchNo { get; set; }
        public int Qty { get; set; }
        public Nullable<int> RIId { get; set; }
        public Nullable<int> BranchInventoryByBatchId { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
    
        public virtual BranchInventoryByBatch BranchInventoryByBatch { get; set; }
        public virtual RunningInventory RunningInventory { get; set; }
    }
}
