//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchInventorySummary
    {
        public BranchInventorySummary()
        {
            this.RunningInventories = new HashSet<RunningInventory>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> TotalInventory { get; set; }
        public Nullable<int> ProductReleased { get; set; }
        public Nullable<int> ProductOnHand { get; set; }
        public Nullable<int> TotalIn { get; set; }
        public Nullable<int> TotalOut { get; set; }
    
        public virtual ICollection<RunningInventory> RunningInventories { get; set; }
    }
}
