//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchInventoryByBatch
    {
        public BranchInventoryByBatch()
        {
            this.BatchNoes = new HashSet<BatchNo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int Qty { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
    
        public virtual ICollection<BatchNo> BatchNoes { get; set; }
    }
}
