//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverylogDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Good { get; set; }
        public Nullable<int> Bad { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public Nullable<int> DeliveryLogsId { get; set; }
    
        public virtual DeliveryLog DeliveryLog { get; set; }
    }
}
