//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceipt
    {
        public DeliveryReceipt()
        {
            this.DRDetails = new HashSet<DRDetail>();
            this.DRTransactions = new HashSet<DRTransaction>();
            this.RunningInventories = new HashSet<RunningInventory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DRTypeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string DRNumber { get; set; }
        public Nullable<int> DRStatusId { get; set; }
        public Nullable<int> TransactionBranchId { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string IboNo { get; set; }
        public string TransactionBy { get; set; }
        public Nullable<int> DRTransactionTypeId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string ReleasedBy { get; set; }
        public string CreatedBy { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<int> BranchClosed { get; set; }
        public Nullable<int> ReleasedBranchId { get; set; }
        public Nullable<int> CreatedBranchId { get; set; }
    
        public virtual DRStatu DRStatu { get; set; }
        public virtual DRTransactionType DRTransactionType { get; set; }
        public virtual DRType DRType { get; set; }
        public virtual ICollection<DRDetail> DRDetails { get; set; }
        public virtual ICollection<DRTransaction> DRTransactions { get; set; }
        public virtual ICollection<RunningInventory> RunningInventories { get; set; }
    }
}
