//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int DRQty { get; set; }
        public int DRCloseQty { get; set; }
        public Nullable<int> DRId { get; set; }
    
        public virtual DeliveryReceipt DeliveryReceipt { get; set; }
    }
}
