//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRTransactionType
    {
        public DRTransactionType()
        {
            this.DeliveryReceipts = new HashSet<DeliveryReceipt>();
            this.DRTransactions = new HashSet<DRTransaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DeliveryReceipt> DeliveryReceipts { get; set; }
        public virtual ICollection<DRTransaction> DRTransactions { get; set; }
    }
}
