//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRTransaction
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public int Qty { get; set; }
        public Nullable<int> DRId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string TransactionBy { get; set; }
        public Nullable<int> TransactionBranchId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual DeliveryReceipt DeliveryReceipt { get; set; }
        public virtual DRTransactionType DRTransactionType { get; set; }
    }
}
