//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fhpInventoryEntities : DbContext
    {
        public fhpInventoryEntities()
            : base("name=fhpInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<BatchNo> BatchNoes { get; set; }
        public virtual DbSet<BottleType> BottleTypes { get; set; }
        public virtual DbSet<BranchInventoryByBatch> BranchInventoryByBatches { get; set; }
        public virtual DbSet<BranchInventorySummary> BranchInventorySummaries { get; set; }
        public virtual DbSet<DeliverylogDetail> DeliverylogDetails { get; set; }
        public virtual DbSet<DeliveryLog> DeliveryLogs { get; set; }
        public virtual DbSet<DeliveryReceipt> DeliveryReceipts { get; set; }
        public virtual DbSet<DRDetail> DRDetails { get; set; }
        public virtual DbSet<DRStatu> DRStatus { get; set; }
        public virtual DbSet<DRTransaction> DRTransactions { get; set; }
        public virtual DbSet<DRTransactionType> DRTransactionTypes { get; set; }
        public virtual DbSet<DRType> DRTypes { get; set; }
        public virtual DbSet<InitialAdditionalHistory> InitialAdditionalHistories { get; set; }
        public virtual DbSet<PRDetail> PRDetails { get; set; }
        public virtual DbSet<ProdRequest> ProdRequests { get; set; }
        public virtual DbSet<PRStatu> PRStatus { get; set; }
        public virtual DbSet<PRTransactionType> PRTransactionTypes { get; set; }
        public virtual DbSet<ReleasingActionType> ReleasingActionTypes { get; set; }
        public virtual DbSet<ReleasingHistory> ReleasingHistories { get; set; }
        public virtual DbSet<ReplenishmentDetail> ReplenishmentDetails { get; set; }
        public virtual DbSet<ReplenishmentHistory> ReplenishmentHistories { get; set; }
        public virtual DbSet<RunningInventory> RunningInventories { get; set; }
        public virtual DbSet<SLIDetail> SLIDetails { get; set; }
        public virtual DbSet<SLIStatu> SLIStatus { get; set; }
        public virtual DbSet<StockLimitIncrease> StockLimitIncreases { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TransferHistory> TransferHistories { get; set; }
        public virtual DbSet<TransferRemark> TransferRemarks { get; set; }
    }
}
