//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialAdditionalHistory
    {
        public InitialAdditionalHistory()
        {
            this.RunningInventories = new HashSet<RunningInventory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int Qty { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<int> BranchIdTo { get; set; }
        public Nullable<int> BranchIdFrom { get; set; }
        public string Username { get; set; }
        public Nullable<int> BadQty { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Receivedby { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual ICollection<RunningInventory> RunningInventories { get; set; }
    }
}
