//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CurrentOnHand { get; set; }
        public Nullable<int> QuantityGiven { get; set; }
        public Nullable<int> QuantityNeeded { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> QuantityReceived { get; set; }
    
        public virtual ProdRequest ProdRequest { get; set; }
    }
}
