//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdRequest
    {
        public ProdRequest()
        {
            this.PRDetails = new HashSet<PRDetail>();
            this.RunningInventories = new HashSet<RunningInventory>();
            this.TransferRemarks = new HashSet<TransferRemark>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string NameRequested { get; set; }
        public Nullable<int> BranchToRequest { get; set; }
        public Nullable<int> BranchRequested { get; set; }
        public string PREQNo { get; set; }
        public string PRELNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string Approvedby { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public Nullable<int> PRTransactionTypeId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        public virtual ICollection<PRDetail> PRDetails { get; set; }
        public virtual PRStatu PRStatu { get; set; }
        public virtual PRTransactionType PRTransactionType { get; set; }
        public virtual ICollection<RunningInventory> RunningInventories { get; set; }
        public virtual ICollection<TransferRemark> TransferRemarks { get; set; }
    }
}
