//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRStatu
    {
        public PRStatu()
        {
            this.ProdRequests = new HashSet<ProdRequest>();
            this.TransferRemarks = new HashSet<TransferRemark>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProdRequest> ProdRequests { get; set; }
        public virtual ICollection<TransferRemark> TransferRemarks { get; set; }
    }
}
