//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int CurrentQtyLimit { get; set; }
        public int RequestedQtyLimit { get; set; }
        public int ApproveQtyLimit { get; set; }
        public Nullable<int> SLIID { get; set; }
    
        public virtual StockLimitIncrease StockLimitIncrease { get; set; }
    }
}
