//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLimitIncrease
    {
        public StockLimitIncrease()
        {
            this.SLIDetails = new HashSet<SLIDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BranchRequested { get; set; }
        public Nullable<int> BranchTo { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string RequestedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual ICollection<SLIDetail> SLIDetails { get; set; }
        public virtual SLIStatu SLIStatu { get; set; }
    }
}
