//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.DeliveryLogs = new HashSet<DeliveryLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Company { get; set; }
        public Nullable<bool> Person { get; set; }
        public string ContactInfo { get; set; }
    
        public virtual ICollection<DeliveryLog> DeliveryLogs { get; set; }
    }
}
