//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRPI.Enterprise.FHPInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHistory
    {
        public TransferHistory()
        {
            this.RunningInventories = new HashSet<RunningInventory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> TransferFrom { get; set; }
        public Nullable<int> TransferTo { get; set; }
        public string Username { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Receivedby { get; set; }
    
        public virtual ICollection<RunningInventory> RunningInventories { get; set; }
    }
}
